### ISSUE TITLE
Question about project function

### ISSUE THREAD

**Issue by E4ck** [QualiSystems/Huawei-VRP-Shell#38]
Hi, 
This project is just a package for the Huawei cli command?
Is it related to the command of Huawei vrp system?

**Comment by Costya-Y** [comment]
Hi @E4ck 

Yes, it's built for Huawei VRP.

Thank you,
Costya

**Comment by danmichlin** [comment]
Hi @E4ck ,
if you require any additional information related to the usage of this project, you can contact Moshe.A@Quali.com .

**Comment by E4ck** [comment]
Ok, Thanks

**Comment by Costya-Y** [comment]
Thank you @E4ck 
Will close this issue for now
